### ISSUE TITLE
Allow configuration from within nerdlet rather than requiring config via .js and .json files

### ISSUE THREAD

**Issue by danielgolden** [newrelic/nr1-customer-journey#27]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
If you want to configure this app to work for you right now you have to edit `nerdlets/customer-journey/dummyData.json` and `journeyConfig.js`. 

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour
We should allow configuration without the need to edit code, so you can just do it all from inside of the nerdlet.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

**Comment by tangollama** [comment]
Addressed functionally.
