### ISSUE TITLE
stepAvailability stat breaks on null value returns

### ISSUE THREAD

**Issue by andrew-lozoya** [newrelic/nr1-customer-journey#3]
stepAvailability stat breaks if SELECT percentage(count(*) ... returns a null value for zero returns. 
E.G. : Failed prop type: The prop `value` is marked as required in `DataPoint`, but its value is `null`.

This was by design no doubt but in some cases like mine, a series chevron may not report any transaction counts at the very end of a journey such as optionally reviewing an invoice after the order is placed.

To solve for this exact scenario I suggest we use a ternary operator instead...

customer-journey/statCell.js

@ Line 123: `const value = (stat.ref == 'stepAvailability' && rs[keys[0]] == null) ? 0 : rs[keys[0]];`

@danielgolden @tangollama

**Comment by tangollama** [comment]
@andrew-lozoya any interest in looking into this for a PR / fix.

**Comment by tangollama** [comment]
@andrew-lozoya I believe this fixed. Closing.
