### ISSUE TITLE
Confirmed NPM Install Error

### ISSUE THREAD

**Issue by DarrenDoyle** [newrelic/nr1-customer-journey#49]
Downloaded the latest version. 

Here are the steps I did to reproduce the Error: 

nr1 profiles:default  
nr1 nerdpack:clean
npm install

npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm ERR! Cannot convert undefined or null to object

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ddoyle/.npm/_logs/2021-10-28T16_03_12_456Z-debug.log

```
1220 timing metavuln:packument:nr1-funnel-component Completed in 1002ms
1221 verbose stack TypeError: Cannot convert undefined or null to object
1221 verbose stack     at Function.keys (<anonymous>)
1221 verbose stack     at Advisory.load (/Users/ddoyle/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.
[2021-10-28T16_03_12_456Z-debug.log](https://github.com/newrelic/nr1-customer-journey/files/7435763/2021-10-28T16_03_12_456Z-debug.log)
js:102:33)
1221 verbose stack     at Calculator.[calculate] (/Users/ddoyle/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:59:14)
1221 verbose stack     at async Promise.all (index 10)
1221 verbose stack     at async Map.[init] (/Users/ddoyle/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:192:7)
1221 verbose stack     at async Map.run (/Users/ddoyle/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:110:7)
1222 verbose cwd /Users/ddoyle/Downloads/nr1-customer-journey-develop 2
1223 verbose Darwin 20.6.0
```

**Comment by DarrenDoyle** [comment]
[2021-10-28T16_03_12_456Z-debug.log](https://github.com/newrelic/nr1-customer-journey/files/7435767/2021-10-28T16_03_12_456Z-debug.log)

**Comment by jpvajda** [comment]
the fix may be as simple as running npm install on the application to update the packages... or it could be something more complex.

**Comment by rudouglas** [comment]
This issue happens when you try to build with Node 16, it builds and starts fine with Node 12 so i've advised to use that instead. Closing out for now
